# Generated by Django 6.0.2 on 2026-02-24 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Tu Nombre')),
                ('calificacion', models.IntegerField(choices=[(1, '1 Estrellas'), (2, '2 Estrellas'), (3, '3 Estrellas'), (4, '4 Estrellas'), (5, '5 Estrellas')])),
                ('mensaje', models.TextField(verbose_name='¿Qué te parecieron los duendes?')),
                ('opinion', models.TextField(verbose_name='¿Qué te pareció la experiencia en la aplicación?')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
