# Generated by Django 6.0.2 on 2026-02-24 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_alter_producto_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='estatura',
            field=models.PositiveIntegerField(default=0, help_text='Estatura en cm'),
        ),
    ]
