# Generated by Django 6.0.2 on 2026-02-24 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_producto_estatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='esta_pedido',
            field=models.BooleanField(default=False, verbose_name='Pedido'),
        ),
    ]
