# Generated by Django 6.0.2 on 2026-02-24 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0004_producto_esta_pedido'),
    ]

    operations = [
    ]
