# Generated by Django 6.0.2 on 2026-02-24 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0005_auto_20260224_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='esta_pedido',
            field=models.BooleanField(default=False),
        ),
    ]
